#!/usr/bin/env bash

tool=${1:-"help"}

if [ "$#" -eq 2 ]
then
  path1=$(realpath $2)
  file1=$(basename $path1)
  echo $path1
  echo $file1
  docker run --rm -v "$path1":/tmp/"$file1" jonathanhuston/slatescript-tools "$1" /tmp/"$file1"
elif [ "$#" -eq 3 ]
then
  path1=$(realpath $2)
  path2=$(realpath $3)
  file1=$(basename $path1)
  file2=$(basename $path2)
  docker run --rm -v "$path1":/tmp/"$file1" -v "$path2":/tmp/"$file2" jonathanhuston/slatescript-tools "$1" /tmp/"$file1" /tmp/"$file2"
else
  docker run --rm jonathanhuston/slatescript-tools "$1"
fi
